name: web
on:
  push:
    branches:
      - "master"
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Sync node version and setup cache
        uses: actions/setup-node@v4
        with:
          node-version: "node"
          cache: "pnpm"
          cache-dependency-path: "web/pnpm-lock.yaml"
      - name: Install dependencies
        run: |
          cd web
          pnpm install --no-frozen-lockfile
      - name: Build
        run: |
          cd web
          pnpm build
          cp dist/index.html dist/404.html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: web/dist
